name: Test and Publish

on:
  release:
    types: [created, prereleased]

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup prerequisites
      uses: ./.github/actions/setup

    - name: Build project
      continue-on-error: false
      uses: ./.github/actions/build-project

    - name: Run tests
      continue-on-error: false
      uses: ./.github/actions/run-tests

    - name: Publish to GitHub Packages
      continue-on-error: false
      uses: ./.github/actions/publish
