name: Test and Publish

on:
  release:
    types: [created, prereleased]

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Setup prerequisites
      uses: ./.github/actions/setup/action.yml

    - name: Build project
      continue-on-error: false
      uses: ./.github/actions/build-project/action.yml

    - name: Run tests
      continue-on-error: false
      uses: ./.github/actions/run-tests/action.yml

    - name: Publish to GitHub Packages
      continue-on-error: false
      run: ./.github/actions/publish/action.yml
